"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const cors_1 = __importDefault(require("cors"));
const express_1 = __importDefault(require("express"));
const env_1 = require("./config/env");
const AuthenticateAdminUseCase_1 = require("./application/use-cases/AuthenticateAdminUseCase");
const AuthenticateStudentUseCase_1 = require("./application/use-cases/AuthenticateStudentUseCase");
const AuthenticateTeacherUseCase_1 = require("./application/use-cases/AuthenticateTeacherUseCase");
const CreateContactInquiryUseCase_1 = require("./application/use-cases/CreateContactInquiryUseCase");
const CreateStudentRegistrationUseCase_1 = require("./application/use-cases/CreateStudentRegistrationUseCase");
const CreateTeacherRegistrationUseCase_1 = require("./application/use-cases/CreateTeacherRegistrationUseCase");
const ManageAttendanceRecordsUseCase_1 = require("./application/use-cases/ManageAttendanceRecordsUseCase");
const ManageEnrolmentApplicationsUseCase_1 = require("./application/use-cases/ManageEnrolmentApplicationsUseCase");
const ManageTeacherClassesUseCase_1 = require("./application/use-cases/ManageTeacherClassesUseCase");
const ManageRegistrationApprovalsUseCase_1 = require("./application/use-cases/ManageRegistrationApprovalsUseCase");
const MongoDatabase_1 = require("./infrastructure/database/MongoDatabase");
const MongoAttendanceRecordRepository_1 = require("./infrastructure/repositories/MongoAttendanceRecordRepository");
const MongoContactInquiryRepository_1 = require("./infrastructure/repositories/MongoContactInquiryRepository");
const MongoEnrolmentApplicationRepository_1 = require("./infrastructure/repositories/MongoEnrolmentApplicationRepository");
const MongoStudentRegistrationRepository_1 = require("./infrastructure/repositories/MongoStudentRegistrationRepository");
const MongoTeacherClassRepository_1 = require("./infrastructure/repositories/MongoTeacherClassRepository");
const MongoTeacherRegistrationRepository_1 = require("./infrastructure/repositories/MongoTeacherRegistrationRepository");
const AdminRegistrationController_1 = require("./presentation/controllers/AdminRegistrationController");
const AttendanceRecordController_1 = require("./presentation/controllers/AttendanceRecordController");
const AuthController_1 = require("./presentation/controllers/AuthController");
const ContactController_1 = require("./presentation/controllers/ContactController");
const EnrolmentApplicationController_1 = require("./presentation/controllers/EnrolmentApplicationController");
const StudentRegistrationController_1 = require("./presentation/controllers/StudentRegistrationController");
const TeacherClassController_1 = require("./presentation/controllers/TeacherClassController");
const TeacherRegistrationController_1 = require("./presentation/controllers/TeacherRegistrationController");
const routes_1 = require("./presentation/routes");
const errorHandler_1 = require("./presentation/middlewares/errorHandler");
const notFoundHandler_1 = require("./presentation/middlewares/notFoundHandler");
const app = (0, express_1.default)();
const contactInquiryRepository = new MongoContactInquiryRepository_1.MongoContactInquiryRepository(MongoDatabase_1.mongoDatabase);
const createContactInquiryUseCase = new CreateContactInquiryUseCase_1.CreateContactInquiryUseCase(contactInquiryRepository);
const contactController = new ContactController_1.ContactController(createContactInquiryUseCase);
const studentRegistrationRepository = new MongoStudentRegistrationRepository_1.MongoStudentRegistrationRepository(MongoDatabase_1.mongoDatabase);
const createStudentRegistrationUseCase = new CreateStudentRegistrationUseCase_1.CreateStudentRegistrationUseCase(studentRegistrationRepository);
const studentRegistrationController = new StudentRegistrationController_1.StudentRegistrationController(createStudentRegistrationUseCase);
const teacherRegistrationRepository = new MongoTeacherRegistrationRepository_1.MongoTeacherRegistrationRepository(MongoDatabase_1.mongoDatabase);
const createTeacherRegistrationUseCase = new CreateTeacherRegistrationUseCase_1.CreateTeacherRegistrationUseCase(teacherRegistrationRepository);
const teacherRegistrationController = new TeacherRegistrationController_1.TeacherRegistrationController(createTeacherRegistrationUseCase);
const teacherClassRepository = new MongoTeacherClassRepository_1.MongoTeacherClassRepository(MongoDatabase_1.mongoDatabase);
const manageTeacherClassesUseCase = new ManageTeacherClassesUseCase_1.ManageTeacherClassesUseCase(teacherClassRepository, teacherRegistrationRepository);
const teacherClassController = new TeacherClassController_1.TeacherClassController(manageTeacherClassesUseCase);
const enrolmentApplicationRepository = new MongoEnrolmentApplicationRepository_1.MongoEnrolmentApplicationRepository(MongoDatabase_1.mongoDatabase);
const manageEnrolmentApplicationsUseCase = new ManageEnrolmentApplicationsUseCase_1.ManageEnrolmentApplicationsUseCase(enrolmentApplicationRepository, studentRegistrationRepository, teacherRegistrationRepository, teacherClassRepository);
const enrolmentApplicationController = new EnrolmentApplicationController_1.EnrolmentApplicationController(manageEnrolmentApplicationsUseCase);
const attendanceRecordRepository = new MongoAttendanceRecordRepository_1.MongoAttendanceRecordRepository(MongoDatabase_1.mongoDatabase);
const manageAttendanceRecordsUseCase = new ManageAttendanceRecordsUseCase_1.ManageAttendanceRecordsUseCase(attendanceRecordRepository);
const attendanceRecordController = new AttendanceRecordController_1.AttendanceRecordController(manageAttendanceRecordsUseCase);
const authenticateStudentUseCase = new AuthenticateStudentUseCase_1.AuthenticateStudentUseCase(studentRegistrationRepository);
const authenticateTeacherUseCase = new AuthenticateTeacherUseCase_1.AuthenticateTeacherUseCase(teacherRegistrationRepository);
const authenticateAdminUseCase = new AuthenticateAdminUseCase_1.AuthenticateAdminUseCase();
const authController = new AuthController_1.AuthController(authenticateStudentUseCase, authenticateTeacherUseCase, authenticateAdminUseCase);
const manageRegistrationApprovalsUseCase = new ManageRegistrationApprovalsUseCase_1.ManageRegistrationApprovalsUseCase(studentRegistrationRepository, teacherRegistrationRepository);
const adminRegistrationController = new AdminRegistrationController_1.AdminRegistrationController(manageRegistrationApprovalsUseCase, createTeacherRegistrationUseCase);
app.use((0, cors_1.default)({
    origin: env_1.env.corsOrigins,
}));
app.use(express_1.default.json({ limit: "2mb" }));
app.use("/api", (0, routes_1.createApiRoutes)(contactController, studentRegistrationController, teacherRegistrationController, authController, adminRegistrationController, authenticateAdminUseCase, teacherClassController, authenticateTeacherUseCase, enrolmentApplicationController, authenticateStudentUseCase, attendanceRecordController));
app.use(notFoundHandler_1.notFoundHandler);
app.use(errorHandler_1.errorHandler);
exports.default = app;
